[font]
size = 9
builtin_box_drawing = true

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
# opacity = 0.95

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"
