[font]
size = 8
builtin_box_drawing = true

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.9
decorations = "None"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"
