[font]
size = 12.0
builtin_box_drawing = true

[font.normal]
family = "CaskaydiaCove Nerd Font"
# family = "Cascadia Code NF"
style = "Regular"

[font.bold]
family = "CaskaydiaCove Nerd Font"
# family = "Cascadia Code NF"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font"
# family = "Cascadia Code NF"
style = "Italic"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
# family = "Cascadia Code NF"
style = "Bold Italic"
